version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", '-d', 'postgres' ]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: src/
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/backend/src
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db:
